In [5]:
import json
import pandas as pd

# Leer el JSON
with open("../data/temp_raw/standings_2021.json", "r", encoding="utf-8") as f:
    raw_data = json.load(f)

# Extraer la tabla de posiciones
table = raw_data["standings"][0]["table"]

# Normalizar a DataFrame
df = pd.json_normalize(table)

# Mostrar columnas clave
df[["position", "team.name", "playedGames", "points", "won", "draw", "lost", "goalsFor", "goalsAgainst", "goalDifference"]]

,position,team.name,playedGames,points,won,draw,lost,goalsFor,goalsAgainst,goalDifference
0,1,Liverpool FC,35,82,25,7,3,81,35,46
1,2,Arsenal FC,35,67,18,13,4,64,31,33
2,3,Manchester City FC,35,64,19,7,9,67,43,24
3,4,Newcastle United FC,35,63,19,6,10,66,45,21
4,5,Chelsea FC,35,63,18,9,8,62,41,21
5,6,Nottingham Forest FC,35,61,18,7,10,54,42,12
6,7,Aston Villa FC,35,60,17,9,9,55,49,6
7,8,AFC Bournemouth,35,53,14,11,10,55,42,13
8,9,Brentford FC,35,52,15,7,13,62,53,9
9,10,Brighton & Hove Albion FC,35,52,13,13,9,57,56,1
10,11,Fulham FC,35,51,14,9,12,50,47,3
11,12,Crystal Palace FC,35,46,11,13,11,44,48,-4
12,13,Wolverhampton Wanderers FC,35,41,12,5,18,51,62,-11
13,14,Everton FC,35,39,8,15,12,36,43,-7
14,15,Manchester United FC,35,39,10,9,16,42,51,-9
15,16,Tottenham Hotspur FC,35,38,11,5,19,63,57,6
16,17,West Ham United FC,35,37,9,10,16,40,59,-19
17,18,Ipswich Town FC,35,22,4,10,21,35,76,-41
18,19,Leicester City FC,35,21,5,6,24,29,76,-47
19,20,Southampton FC,35,11,2,5,28,25,82,-57